name: R2 Cleanup

on:
  schedule:
    - cron: '0 2 * * *'  # Every day at 2 AM
  workflow_dispatch:

jobs:
  cleanup:
    uses: DoYouHost/workflows/.github/workflows/cleanup-r2.yml@main
    with:
      directory: 'serverCoolingFanController'
      days_old: '30'
    secrets:
      CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
      CF_ACCESS_KEY_ID: ${{ secrets.CF_ACCESS_KEY_ID }}
      CF_SECRET_ACCESS_KEY: ${{ secrets.CF_SECRET_ACCESS_KEY }}
      CF_BUCKET_NAME: ${{ secrets.CF_BUCKET_NAME }}